# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    containerRegistry: 'dockerhub-thina'
    command: login

- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'dockerhub-thina'
    repository: 'thinalai/thina-task6demo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: 'task6'
